global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.27.79:9090','172.31.18.255:9100', '172.31.23.96:9100']
